sudo: false
language: python
python: '3.5'
env:
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=pypy3
install:
  - travis_retry pip install tox
script:
  - tox
notifications:
  email: false
